In [21]:
import time
from selenium import webdriver
import json
import pandas as pd
from pandas.io.json import json_normalize

In [22]:
list_android=["samsung", "xiaomi", "realme", "oppo", "vivo"]
# list_android=["vivo"]

empty_dataframe1 = pd.DataFrame()
for page in range (1, 6):
    for i in list_android:
        link= f"https://www.blibli.com/backend/search/products?sort=0&page={page}&start=0&searchTerm={i}&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false"
        print(link)
        driver = webdriver.Chrome(executable_path='C:/Users/User/Downloads/chromedriver_win32/chromedriver.exe')
        driver.get(link)

        aa = driver.page_source
    #     print(aa)

        index_code=int(aa.find('{"code"'))
        index_full=int(len(aa))
        data_aa=aa[index_code:index_full-20]
        # data_aa
        data_aa_json=json.loads(data_aa)
        # data_aa_json
        products_data=data_aa_json['data']['products']
        # products_data
        products_data= json_normalize(products_data)
        # products_data
        df=pd.DataFrame(products_data)
        df = df[['id', 'sku', 'name', 'price.offerPriceDisplay', 'price.discount','rootCategory.name','brand', 'review.rating', 'review.count','location'  ]]
    #     df = df[['id', 'sku']]

        print(len(df))
        empty_dataframe1=empty_dataframe1.append(df, ignore_index = True)

https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=samsung&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false

<ipython-input-22-1a9bab1c9d8f>:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  products_data= json_normalize(products_data)

40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=xiaomi&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=realme&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=oppo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=vivo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=2&start=0&searchTerm=samsung&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=2&start=0&searchTerm=xiaomi&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=2&start=0&searchTerm=realme&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=2&start=0&searchTerm=oppo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=2&start=0&searchTerm=vivo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=3&start=0&searchTerm=samsung&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=3&start=0&searchTerm=xiaomi&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=3&start=0&searchTerm=realme&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=3&start=0&searchTerm=oppo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=3&start=0&searchTerm=vivo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=4&start=0&searchTerm=samsung&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=4&start=0&searchTerm=xiaomi&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=4&start=0&searchTerm=realme&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=4&start=0&searchTerm=oppo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=4&start=0&searchTerm=vivo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=5&start=0&searchTerm=samsung&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=5&start=0&searchTerm=xiaomi&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=5&start=0&searchTerm=realme&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=5&start=0&searchTerm=oppo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=5&start=0&searchTerm=vivo&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=HA-1000002&catIntent=false&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40

In [23]:
list_iphone=["x", "xs", "xr", "8"]
# list_iphone=["x"]

all_df=[]
empty_dataframe2 = pd.DataFrame()
for page in range(1,6):
    for i in list_iphone:
        link= f"https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20{i}&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false"
        print(link)
        driver = webdriver.Chrome(executable_path='C:/Users/User/Downloads/chromedriver_win32/chromedriver.exe')
        driver.get(link)
        aa = driver.page_source
    #     print(aa)

        index_code=int(aa.find('{"code"'))
        index_full=int(len(aa))
        data_aa=aa[index_code:index_full-20]
        # data_aa
        data_aa_json=json.loads(data_aa)
        # data_aa_json
        products_data=data_aa_json['data']['products']
        # products_data
        products_data= json_normalize(products_data)
        # products_data
        df=pd.DataFrame(products_data)
        df = df[['id', 'sku', 'name', 'price.offerPriceDisplay', 'price.discount','rootCategory.name','brand', 'review.rating', 'review.count','location'  ]]
    #     df = df[['id', 'sku']]

        print(len(df))
        empty_dataframe2=empty_dataframe2.append(df, ignore_index = True)

https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20x&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false

<ipython-input-23-479478ca569c>:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  products_data= json_normalize(products_data)

40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xs&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xr&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%208&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20x&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xs&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xr&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%208&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20x&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xs&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xr&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%208&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20x&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xs&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xr&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%208&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20x&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xs&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%20xr&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40
https://www.blibli.com/backend/search/products?sort=0&page=1&start=0&searchTerm=iphone%208&intent=false&merchantSearch=true&multiCategory=true&customUrl=&category=IP-1000001&channelId=web&showFacet=false&userIdentifier=723337755.U.7632644965754952.1633751069&isMobileBCA=false
40

In [24]:
df1=empty_dataframe1

In [25]:
df2=empty_dataframe2

In [26]:
frames=[df1, df2]
df=pd.concat(frames, ignore_index=True)
df

,id,sku,name,price.offerPriceDisplay,price.discount,rootCategory.name,brand,review.rating,review.count,location
0,SAO-60034-01398,SAO-60034-01398,Samsung Galaxy M32 Smartphone [6/128GB],NaN,0,Handphone &amp; Tablet,Samsung,4,643,Kota Tangerang
1,SAO-60034-00889,SAO-60034-00889,Samsung Galaxy M51 Smartphone [128GB/ 8GB],Rp4.299.000,21,Handphone &amp; Tablet,Samsung,4,952,Kota Tangerang
2,PTI-60049-00104,PTI-60049-00104,Samsung Galaxy A22 LTE Smartphone [6 GB/ 128 G...,Rp2.754.000,8,Handphone &amp; Tablet,Samsung,5,1,Kota Medan
3,BIS-56524-00096,BIS-56524-00096,Samsung Galaxy A12 [6 / 128],Rp2.410.000,10,Handphone &amp; Tablet,Samsung,4,20,Kota Jakarta Barat
4,BIS-56524-00094,BIS-56524-00094,Samsung Galaxy A12 6/128,NaN,0,Handphone &amp; Tablet,Samsung,4,12,Kota Jakarta Barat
...,...,...,...,...,...,...,...,...,...,...
1795,RES-70136-00011,RES-70136-00011,NEW APPLE IPHONE 8 256GB ORIGINAL FU GSM GARAN...,Rp3.960.000,41,Handphone &amp; Tablet,Apple,4,3,Kota Jakarta Barat
1796,NUO-70002-00048,NUO-70002-00048,APPLE IPHONE XS 256 GB GARANSI 1 TAHUN GREY GO...,Rp7.750.000,35,Handphone &amp; Tablet,Apple,5,7,Kota Jakarta Barat
1797,NIG-70008-00030,NIG-70008-00030,Apple Iphone 8 Plus Smartphone [256 GB],Rp5.132.000,48,Handphone &amp; Tablet,Apple,0,0,Kota Jakarta Pusat
1798,NUO-70002-00046,NUO-70002-00046,APPLE IPHONE XS MAX 256 GB GARANSI 1 TAHUN GRE...,Rp8.299.000,22,Handphone &amp; Tablet,Apple,5,5,Kota Jakarta Barat
1799,NUO-70002-00021,NUO-70002-00021,APPLE IPHONE 6S PLUS 64GB GARANSI 1 TAHUN GREY...,Rp2.649.000,50,Handphone &amp; Tablet,Apple,5,7,Kota Jakarta Barat

In [27]:
df[38:]

,id,sku,name,price.offerPriceDisplay,price.discount,rootCategory.name,brand,review.rating,review.count,location
38,BEB-70043-00018,BEB-70043-00018,SAMSUNG GALAXY ZFOLD2 - RESMI,NaN,0,Handphone &amp; Tablet,Samsung,5,2,Kota Bandung
39,UNG-60029-00618,UNG-60029-00618,Samsung Galaxy Z Flip 3 5G 256GB - Garansi Res...,Rp15.533.000,2,Handphone &amp; Tablet,Samsung,5,1,Kota Jakarta Utara
40,XIO-60022-00609,XIO-60022-00609,"Xiaomi Redmi 9C (4GB+64GB) DotDrop 6.53"" HD+, ...",Rp1.699.000,0,Handphone &amp; Tablet,Xiaomi,4,451,Kota Tangerang
41,88P-60022-00728,88P-60022-00728,Xiaomi Poco X3 Pro Smartphone [6GB/ 128GB/ H],Rp3.432.000,1,Handphone &amp; Tablet,Xiaomi,5,17,Kota Tangerang
42,PAP-60024-01943,PAP-60024-01943,Xiaomi POCO X3 Pro Smartphone [8GB/256GB] GARA...,Rp3.925.980,2,Handphone &amp; Tablet,Xiaomi,5,4,Kota Surabaya
...,...,...,...,...,...,...,...,...,...,...
1795,RES-70136-00011,RES-70136-00011,NEW APPLE IPHONE 8 256GB ORIGINAL FU GSM GARAN...,Rp3.960.000,41,Handphone &amp; Tablet,Apple,4,3,Kota Jakarta Barat
1796,NUO-70002-00048,NUO-70002-00048,APPLE IPHONE XS 256 GB GARANSI 1 TAHUN GREY GO...,Rp7.750.000,35,Handphone &amp; Tablet,Apple,5,7,Kota Jakarta Barat
1797,NIG-70008-00030,NIG-70008-00030,Apple Iphone 8 Plus Smartphone [256 GB],Rp5.132.000,48,Handphone &amp; Tablet,Apple,0,0,Kota Jakarta Pusat
1798,NUO-70002-00046,NUO-70002-00046,APPLE IPHONE XS MAX 256 GB GARANSI 1 TAHUN GRE...,Rp8.299.000,22,Handphone &amp; Tablet,Apple,5,5,Kota Jakarta Barat
1799,NUO-70002-00021,NUO-70002-00021,APPLE IPHONE 6S PLUS 64GB GARANSI 1 TAHUN GREY...,Rp2.649.000,50,Handphone &amp; Tablet,Apple,5,7,Kota Jakarta Barat

In [28]:
df['price.offerPriceDisplay'] = df['price.offerPriceDisplay'].str.replace('Rp', '')
df['price.offerPriceDisplay'] = df['price.offerPriceDisplay'].str.replace('.', '')
df['price.offerPriceDisplay'] = df['price.offerPriceDisplay'].fillna(0)
df['price.offerPriceDisplay']=df['price.offerPriceDisplay'].apply(int)
df['price.offerPriceDisplay']

0             0
1       4299000
2       2754000
3       2410000
4             0
         ...
1795    3960000
1796    7750000
1797    5132000
1798    8299000
1799    2649000
Name: price.offerPriceDisplay, Length: 1800, dtype: int64

In [29]:
df['name'] = df['name'].str.replace('%', '')

In [30]:
df['id']=df['id'].apply(str)
df['sku']=df['sku'].apply(str)
df['name']=df['name'].apply(str)
df['price.offerPriceDisplay']=df['price.offerPriceDisplay'].apply(str)
df['rootCategory.name']=df['rootCategory.name'].apply(str)
df['brand']=df['brand'].apply(str)
df['location']=df['location'].apply(str)

In [31]:
df.dtypes

id                         object
sku                        object
name                       object
price.offerPriceDisplay    object
price.discount              int64
rootCategory.name          object
brand                      object
review.rating               int64
review.count                int64
location                   object
dtype: object

In [32]:
df['price.offerPriceDisplay']=df['price.offerPriceDisplay'].apply(int)

df.dtypes

id                         object
sku                        object
name                       object
price.offerPriceDisplay     int64
price.discount              int64
rootCategory.name          object
brand                      object
review.rating               int64
review.count                int64
location                   object
dtype: object

In [33]:
df.rename(columns={'rootCategory.name': 'rootCategory_name'}, inplace=True)

In [34]:
df.rename(columns={'price.offerPriceDisplay': 'price_offerPriceDisplay'}, inplace=True)
df.rename(columns={'price.discount': 'price_discount'}, inplace=True)
df.rename(columns={'review.rating': 'review_rating'}, inplace=True)
df.rename(columns={'review.count': 'review_count'}, inplace=True)

In [35]:
df.dtypes

id                         object
sku                        object
name                       object
price_offerPriceDisplay     int64
price_discount              int64
rootCategory_name          object
brand                      object
review_rating               int64
review_count                int64
location                   object
dtype: object

In [36]:
df.isnull()

,id,sku,name,price_offerPriceDisplay,price_discount,rootCategory_name,brand,review_rating,review_count,location
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1795,False,False,False,False,False,False,False,False,False,False
1796,False,False,False,False,False,False,False,False,False,False
1797,False,False,False,False,False,False,False,False,False,False
1798,False,False,False,False,False,False,False,False,False,False
1799,False,False,False,False,False,False,False,False,False,False

In [37]:
import psycopg2

In [38]:

conn_params_dic = {
    "host"      : "localhost",
    "database"  : "postgres",
    "user"      : "postgres",
    "password"  : "1234"
}

In [39]:
def connect(conn_params_dic):
    conn = None
    try:
        print('Connecting to the PostgreSQL...........')
        conn = psycopg2.connect(**conn_params_dic)
        print("Connection successfully..................")
        
    except OperationalError as err:
        # passing exception to function
        show_psycopg2_exception(err)        
        # set the connection to 'None' in case of error
        conn = None
    return conn

In [40]:

def execute_mogrify(conn, df, table):
    """
    Using cursor.mogrify() to build the bulk insert query
    then cursor.execute() to execute the query
    """
    # Create a list of tupples from the dataframe values
    tuples = [tuple(x) for x in df.to_numpy()]
    
#     print(tuples)
    # Comma-separated dataframe columns
    cols = ','.join(list(df.columns))
    
    
#     print(cols)
    # SQL quert to execute
    cursor = conn.cursor()
    values = [cursor.mogrify("(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)", tup).decode('utf8') for tup in tuples]
    query  = "INSERT INTO %s(%s) VALUES " % (table, cols) + ",".join(values)
    
    try:
        cursor.execute(query, tuples)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        conn.rollback()
        cursor.close()
        return 1
    print("execute_mogrify() done")
    cursor.close()

In [41]:
# Connect to the database
conn = connect(conn_params_dic)

# Run the execute_many strategy
execute_mogrify(conn, df, 'please')

Connecting to the PostgreSQL...........
Connection successfully..................
execute_mogrify() done